name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync
    - name: Build package
      run: uv pip build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Publish to PyPI
      run: |
        uv pip publish \
          --repository https://upload.pypi.org/legacy/ \
          --username "__token__" \
          --password "$PYPI_API_TOKEN"
      env:
        PYPI_API_TOKEN: ${{ secrets.REPO_PYPI_API_TOKEN }}
